export const data = [
  {
    id: "1",
    name: "iPhone 13",
    price: "$999",
    image: "https://example.com/iphone-13.png",
    color: "Midnight",
  },
  {
    id: "2",
    name: "Samsung Galaxy S21",
    price: "$799",
    image: "https://example.com/samsung-s21.png",
    color: "Phantom Black",
  },
  {
    id: "3",
    name: "OnePlus 9 Pro",
    price: "$969",
    image: "https://example.com/oneplus-9-pro.png",
    color: "Morning Mist",
  },
  {
    id: "4",
    name: "Google Pixel 6",
    price: "$799",
    image: "https://example.com/google-pixel-6.png",
    color: "Stormy Black",
  },
  {
    id: "5",
    name: "Xiaomi Mi 11",
    price: "$749",
    image: "https://example.com/xiaomi-mi-11.png",
    color: "Midnight Gray",
  },
  {
    id: "6",
    name: "Sony Xperia 1 III",
    price: "$1,299",
    image: "https://example.com/sony-xperia-1-iii.png",
    color: "Frosted Black",
  },
  {
    id: "7",
    name: "LG Velvet 5G",
    price: "$599",
    image: "https://example.com/lg-velvet-5g.png",
    color: "Illusion Sunset",
  },
  {
    id: "8",
    name: "Motorola Moto G Power",
    price: "$249",
    image: "https://example.com/motorola-moto-g-power.png",
    color: "Flash Gray",
  },
  {
    id: "9",
    name: "Nokia 8.3 5G",
    price: "$699",
    image: "https://example.com/nokia-8-3-5g.png",
    color: "Polar Night",
  },
  {
    id: "10",
    name: "Asus ROG Phone 5",
    price: "$999",
    image: "https://example.com/asus-rog-phone-5.png",
    color: "Phantom Black",
  },
  {
    id: "11",
    name: "Realme 8 Pro",
    price: "$299",
    image: "https://example.com/realme-8-pro.png",
    color: "Infinite Blue",
  },
  {
    id: "12",
    name: "OPPO Find X3 Pro",
    price: "$1,199",
    image: "https://example.com/oppo-find-x3-pro.png",
    color: "Gloss Black",
  },
  {
    id: "13",
    name: "ZTE Axon 30 Ultra",
    price: "$749",
    image: "https://example.com/zte-axon-30-ultra.png",
    color: "Black",
  },
];
